spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store_prod
    username: postgres
    password: 130896
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8081
